from node:latest

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json

RUN npm install
RUN npm -g config set user root
RUN npm install -g @angular/cli

copy . /usr/src/app

CMD ng serve --host 0.0.0.0
