# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='email.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x65mail.proto\"%\n\x0c\x45mailRequest\x12\x15\n\x05\x65mail\x18\x01 \x01(\x0b\x32\x06.Email\"*\n\nEmailReply\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\"*\n\rVerifyRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"(\n\x0c\x43heckRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"9\n\x05\x45mail\x12\x11\n\ttoAddress\x18\x01 \x03(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04html\x18\x03 \x01(\t2k\n\x0c\x45mailService\x12,\n\x0bVerifyEmail\x12\x0e.VerifyRequest\x1a\x0b.EmailReply\"\x00\x12-\n\rCheckVerified\x12\r.CheckRequest\x1a\x0b.EmailReply\"\x00\x62\x06proto3'
)




_EMAILREQUEST = _descriptor.Descriptor(
  name='EmailRequest',
  full_name='EmailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='EmailRequest.email', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=52,
)


_EMAILREPLY = _descriptor.Descriptor(
  name='EmailReply',
  full_name='EmailReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='EmailReply.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='EmailReply.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=96,
)


_VERIFYREQUEST = _descriptor.Descriptor(
  name='VerifyRequest',
  full_name='VerifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='VerifyRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='VerifyRequest.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=140,
)


_CHECKREQUEST = _descriptor.Descriptor(
  name='CheckRequest',
  full_name='CheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CheckRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='CheckRequest.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=182,
)


_EMAIL = _descriptor.Descriptor(
  name='Email',
  full_name='Email',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='toAddress', full_name='Email.toAddress', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='Email.subject', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='html', full_name='Email.html', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=241,
)

_EMAILREQUEST.fields_by_name['email'].message_type = _EMAIL
DESCRIPTOR.message_types_by_name['EmailRequest'] = _EMAILREQUEST
DESCRIPTOR.message_types_by_name['EmailReply'] = _EMAILREPLY
DESCRIPTOR.message_types_by_name['VerifyRequest'] = _VERIFYREQUEST
DESCRIPTOR.message_types_by_name['CheckRequest'] = _CHECKREQUEST
DESCRIPTOR.message_types_by_name['Email'] = _EMAIL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailRequest = _reflection.GeneratedProtocolMessageType('EmailRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMAILREQUEST,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:EmailRequest)
  })
_sym_db.RegisterMessage(EmailRequest)

EmailReply = _reflection.GeneratedProtocolMessageType('EmailReply', (_message.Message,), {
  'DESCRIPTOR' : _EMAILREPLY,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:EmailReply)
  })
_sym_db.RegisterMessage(EmailReply)

VerifyRequest = _reflection.GeneratedProtocolMessageType('VerifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYREQUEST,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:VerifyRequest)
  })
_sym_db.RegisterMessage(VerifyRequest)

CheckRequest = _reflection.GeneratedProtocolMessageType('CheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKREQUEST,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:CheckRequest)
  })
_sym_db.RegisterMessage(CheckRequest)

Email = _reflection.GeneratedProtocolMessageType('Email', (_message.Message,), {
  'DESCRIPTOR' : _EMAIL,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:Email)
  })
_sym_db.RegisterMessage(Email)



_EMAILSERVICE = _descriptor.ServiceDescriptor(
  name='EmailService',
  full_name='EmailService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=243,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='VerifyEmail',
    full_name='EmailService.VerifyEmail',
    index=0,
    containing_service=None,
    input_type=_VERIFYREQUEST,
    output_type=_EMAILREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckVerified',
    full_name='EmailService.CheckVerified',
    index=1,
    containing_service=None,
    input_type=_CHECKREQUEST,
    output_type=_EMAILREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAILSERVICE)

DESCRIPTOR.services_by_name['EmailService'] = _EMAILSERVICE

# @@protoc_insertion_point(module_scope)
