version: "3"
services: 

  frontend:
    container_name: angular-app
    build:
      context: ./stocks-app
      dockerfile: Dockerfile-dev
    ports: 
      - "4200:4200"
    volumes: 
      - ./stocks-app:/usr/src/app
    environment: 
      NODE_ENV: development
    depends_on: 
      - api-gateway

  api-gateway:
    container_name: api-gateway
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile-dev
    ports: 
      - "9000:8080"
    depends_on: 
      - redis

  redis:
    container_name: redis-cache
    image: redis
    ports:
      - "6379:6379"
  
  stocks-service:
    container_name: go-stocks
    build:
        context: ./stocks-service
        dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    depends_on: 
      - api-gateway
      - email-service

  users-service:
    container_name: py-users
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports: 
      - "8001:8001"
    depends_on: 
      - api-gateway
      - email-service

  email-service:
    container_name: node-email
    build:
      context: ./email-service
      dockerfile: Dockerfile
    ports: 
      - "5001:5001"
    

  