version: "3"
services: 

  backend:
    container_name: spring-app
    build: 
      context: ./stocks-api
      dockerfile: Dockerfile
    ports: 
      - "9000:8080"

  frontend:
    container_name: angular-app
    build:
      context: ./stocks-app
      dockerfile: Dockerfile-dev
    ports: 
      - "4200:4200"
    volumes: 
      - ./stocks-app:/usr/src/app
    environment: 
      NODE_ENV: development
    depends_on: 
      - backend