version: "3"
services: 

  backend:
    container_name: spring-app
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports: 
      - "9000:8080"
    depends_on: 
      - stocks-service

  frontend:
    container_name: angular-app
    build:
      context: ./stocks-app
      dockerfile: Dockerfile-dev
    ports: 
      - "4200:4200"
    volumes: 
      - ./stocks-app:/usr/src/app
    environment: 
      NODE_ENV: development
    depends_on: 
      - backend
  
  stocks-service:
    container_name: go-stocks
    build:
        context: ./stocks-service
        dockerfile: Dockerfile
    ports: 
      - "8000:8000"