apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
      tier: web
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        tier: web
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: redis
          imagePullPolicy: Always
          ports:
          - containerPort: 6379
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http