apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/existing: replace
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    app: {{ .Values.service.app }}
