{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "users.serviceAccountName" . }}
  labels:
{{ include "users.labels" . | indent 4 }}
{{- end -}}
