apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: email
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  selector:
    matchLabels:
      app: email
      tier: web
  template:
    metadata:
      labels:
        app: email
        tier: web
    spec:
      containers:
      - name: node-email
        image: us.gcr.io/stocks-app-email/node-email:$GITHUB_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 5001