apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
      tier: web
  template:
    metadata:
      labels:
        app: gateway
        tier: web
    spec:
      containers:
      - name: api-gateway
        image: us.gcr.io/stocks-app-email/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080