apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  selector:
    matchLabels:
      app: users
      tier: web
  template:
    metadata:
      labels:
        app: users
        tier: web
    spec:
      containers:
      - name: py-users
        image: us.gcr.io/stocks-app-email/py-users:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001