apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ .Values.service.app }}
