// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stocks.proto

/*
Package stocks is a generated protocol buffer package.

It is generated from these files:
	stocks.proto

It has these top-level messages:
	Request
	TimeRequest
	Response
*/
package stocks

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	StockSymbol string `protobuf:"bytes,1,opt,name=stockSymbol" json:"stockSymbol,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetStockSymbol() string {
	if m != nil {
		return m.StockSymbol
	}
	return ""
}

type TimeRequest struct {
	Symbol string `protobuf:"bytes,1,opt,name=Symbol,json=symbol" json:"Symbol,omitempty"`
	Time   string `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
}

func (m *TimeRequest) Reset()                    { *m = TimeRequest{} }
func (m *TimeRequest) String() string            { return proto.CompactTextString(m) }
func (*TimeRequest) ProtoMessage()               {}
func (*TimeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TimeRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TimeRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type Response struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	Status   int32  `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*TimeRequest)(nil), "TimeRequest")
	proto.RegisterType((*Response)(nil), "Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StockService service

type StockServiceClient interface {
	GetStockPrice(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GetStockOptions(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GetTimeSeries(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*Response, error)
}

type stockServiceClient struct {
	cc *grpc.ClientConn
}

func NewStockServiceClient(cc *grpc.ClientConn) StockServiceClient {
	return &stockServiceClient{cc}
}

func (c *stockServiceClient) GetStockPrice(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/StockService/GetStockPrice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) GetStockOptions(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/StockService/GetStockOptions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) GetTimeSeries(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/StockService/GetTimeSeries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StockService service

type StockServiceServer interface {
	GetStockPrice(context.Context, *Request) (*Response, error)
	GetStockOptions(context.Context, *Request) (*Response, error)
	GetTimeSeries(context.Context, *TimeRequest) (*Response, error)
}

func RegisterStockServiceServer(s *grpc.Server, srv StockServiceServer) {
	s.RegisterService(&_StockService_serviceDesc, srv)
}

func _StockService_GetStockPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetStockPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StockService/GetStockPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetStockPrice(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_GetStockOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetStockOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StockService/GetStockOptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetStockOptions(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_GetTimeSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetTimeSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StockService/GetTimeSeries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetTimeSeries(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StockService",
	HandlerType: (*StockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockPrice",
			Handler:    _StockService_GetStockPrice_Handler,
		},
		{
			MethodName: "GetStockOptions",
			Handler:    _StockService_GetStockOptions_Handler,
		},
		{
			MethodName: "GetTimeSeries",
			Handler:    _StockService_GetTimeSeries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stocks.proto",
}

func init() { proto.RegisterFile("stocks.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0xc9, 0x4f,
	0xce, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe6, 0x62, 0x0f, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe0, 0xe2, 0x06, 0x4b, 0x05, 0x57, 0xe6, 0x26, 0xe5, 0xe7, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x0b, 0x29, 0x59, 0x72, 0x71, 0x87, 0x64, 0xe6, 0xa6,
	0xc2, 0x34, 0x88, 0x71, 0xb1, 0xa1, 0xa8, 0x65, 0x2b, 0x06, 0xf3, 0x84, 0x84, 0xb8, 0x58, 0x4a,
	0x32, 0x73, 0x53, 0x25, 0x98, 0xc0, 0xa2, 0x60, 0xb6, 0x92, 0x1d, 0x17, 0x47, 0x50, 0x6a, 0x71,
	0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x14, 0x17, 0x47, 0x11, 0x94, 0x0d, 0xd5, 0x09, 0xe7, 0x83,
	0xcc, 0x2c, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x06, 0xeb, 0x66, 0x0d, 0x82, 0xf2, 0x8c, 0xda, 0x18,
	0xb9, 0x78, 0x82, 0xc1, 0x4e, 0x49, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x52, 0xe1, 0xe2, 0x75,
	0x4f, 0x2d, 0x01, 0x0b, 0x05, 0x14, 0x81, 0x04, 0x38, 0xf4, 0xa0, 0xee, 0x92, 0xe2, 0xd4, 0x83,
	0x5b, 0xa5, 0xc6, 0xc5, 0x0f, 0x53, 0xe5, 0x5f, 0x50, 0x92, 0x99, 0x9f, 0x57, 0x8c, 0x5d, 0x9d,
	0x06, 0xd8, 0x34, 0x90, 0xe7, 0x82, 0x53, 0x8b, 0x32, 0x53, 0x8b, 0x85, 0x78, 0xf4, 0x90, 0x7c,
	0x8a, 0xa4, 0x32, 0x89, 0x0d, 0x1c, 0x6e, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0x3d,
	0x26, 0x8c, 0x47, 0x01, 0x00, 0x00,
}
