apiVersion: v1
kind: Service
metadata:
  name: stocks-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: stocks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks
  labels:
    app: stocks
spec:
  selector:
    matchLabels:
      app: stocks
      tier: web
  template:
    metadata:
      labels:
        app: stocks
        tier: web
    spec:
      containers:
      - name: go-stocks
        image: us.gcr.io/stocks-app-email/go-stocks:$GITHUB_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 8000