# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Dat Jar Boi, then deploy dat Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-central1
  GKE_CLUSTER: stocks-cluster
  IMAGE: api-gateway
  REGISTRY_HOSTNAME: us.gcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./api-gateway
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: see where we are
      run: ls -la
      working-directory: ${{env.working-directory}}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{env.working-directory}}
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ${{env.working-directory}}
    - name: package jar file
      uses: actions/upload-artifact@v1  
      with:
        name: gateway
        path: ${{env.working-directory}}/build/libs
  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    env:
      working-directory: ./api-gateway
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
          name: gateway
          path: ${{env.working-directory}}/build/libs
    - run: cat ${{env.working-directory}}/build/libs/gateway.jar
    - name: check for new Jar
      run: ls -la
      working-directory: ${{env.working-directory}}/build/libs

